name: Ruby

on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.0
    - name: Run the default task
      run: |
        gem install bundler -v 2.2.11
        bundle install
        RUBYOPT='--enable-frozen-string-literal' bundle exec rake spec
        bundle exec rake standard
